name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Extract tag name
      id: tag
      run: echo "::set-output name=value::${GITHUB_REF##*/}"
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: 2.6
    
    - name: Install dependencies
      run: bundle install
    
    - name: Create package
      run: bundle exec rake package

    - name: Get Directory
      id: folder
      run: |
        cd packaging/builds
        echo ::set-output name=name::$(ls)
    
    - name: Get Packages
      id: binaries
      run: |
        cd packaging/builds/${{ steps.folder.outputs.name }}
        deb=$(find . -type f -name '*.deb')
        rpm=$(find . -type f -name "*.rpm")
        echo ::set-output name=deb_file::"${deb:2}"
        echo ::set-output name=rpm_file::"${rpm:2}"

    - name: Create Release # https://hub.github.com/hub-release.1.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd packaging/builds/
        hub release create ${{ steps.tag.outputs.value }} \
        -a ${{ steps.folder.outputs.name }}/${{ steps.binaries.outputs.deb_file }} \
        -a ${{ steps.folder.outputs.name }}/${{ steps.binaries.outputs.rpm_file }} \
        -m "Version ${{ steps.folder.outputs.name }}

        Release of version ${{ steps.folder.outputs.name }} of the Shopify App CLI
        Please refer to [CHANGELOG](https://github.com/Shopify/shopify-app-cli/blob/master/CHANGELOG.md) for details."
